### ISSUE TITLE
Unable to download a UniRef database

### ISSUE THREAD

**Issue by roshni-b** [bmorganpalmer/humann#1]
`CRITICAL ERROR: Unable to download and extract from URL: http://huttenhower.sph.harvard.edu/humann2_data/uniprot/uniref_annotated/uniref50_annotated_1_1.tar.gz`

**Comment by bmorganpalmer** [comment]
Sorry the link is no longer valid and I don't have another reference.
Best,
bmp

**Comment by levinyi** [comment]
so，where can we download the databases? any dropbox? google driver? 
http://huttenhower.sph.harvard.edu/humann2_data/full_mapping_v201901.tar.gz
